### PR TITLE
62x Remove upgrade playbooks

### PR DESCRIPTION
**Pull request by domenicbove**
# Description

Now that all.yml successfully upgrades our components in an idempotent way, we no longer need these playbooks. New upgrade docs will be published with the 6.2.0 release on docs.confluent.io

Fixes # (https://github.com/confluentinc/cp-ansible/issues/588)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

all.yml upgrades have been tested

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] Any variable changes have been validated to be backwards compatible

### CODE REVIEW

**Comment by domenicbove** [comment]
@erikgb Your github issue says to deprecate, but I'm leaning toward removing the upgrade playbooks w 6.2.0 - wdyt? I'd rather get our users moved over to the idempotent upgrades

**Comment by erikgb** [comment]
@domenicbove The ultimate goal should be to delete the upgrade playbooks, which will give us less to maintain. I am fine removing noe, since we use the idempotent upgrade. You know your customers best! 😉

**Comment by domenicbove** [comment]
@rohit2b I'm on board with removing these old playbooks in favor of the new upgrade strategy because it provides more capabilities (like downgrades, idempotency, confluent-server<->kafka switches). But just want one final approval. The procedure is pretty much the same as the old, just new commands so I think it shouldn't be met with too much friction.

**Review by erikgb — APPROVED** [review]

**Comment by rohit2b** [comment]
+1 from me

**Review by rohit2b — APPROVED** [review]

**Pull request merged**
