### PR TITLE
Fix variable error in PR 991

### PR DESCRIPTION
**Pull request by nsharma-git**
# Description

Update rbac flag for ksql cluster registration

Fixes # (issue)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

[Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

https://jenkins.confluent.io/job/cp-ansible-on-demand/168/

**Test Configuration**:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] Any variable changes have been validated to be backwards compatible

### CODE REVIEW

**Review by utkarsh5474 — APPROVED** [review]
LGTM

**Comment by utkarsh5474** [comment]
Logic similar to what was changed in #991 is also present in other parts of our code. I haven't gone through them in detail but could it possible we apply similar changes therein? For ex - kafka connect here - https://github.com/confluentinc/cp-ansible/blob/6.2.x/roles/confluent.kafka_connect/tasks/main.yml#L278 , https://github.com/confluentinc/cp-ansible/blob/6.2.x/roles/confluent.kafka_connect/tasks/register_cluster.yml

**Comment by DennisFederico** [comment]
I agree, I saw the logic for registering the cluster, reused in connect but wanted the approval/review for one place (ksql) first
I'll submit the change for connect as soon as I have the time (if no body else beats me to it)

**Review by DennisFederico — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
