### PR TITLE
Refactored from multiple folders roles to a single role

### PR DESCRIPTION
**Pull request by vfoucault**
* all defaults / handlers moved to defaults / handlers main.yml
* all tasks from confluent.{role} moved to tasks/{role}/
* all templates from confluent.{role} moved to templates/{role}/

* Merged defaults
* added a main.yml that will always call preflight & common and call
all roles specified in variable confluent_roles (list)

this PR fixes Issue #16

### CODE REVIEW

**Comment by vfoucault** [comment]
@cotedm Here you go.
This first part is only the refactor to a single role.

**Comment by vfoucault** [comment]
@cotedm Got some troubles today rebasing work. It should be ok for the 5 first PR. All the RP marked as WIP aren't ready yet.

Let me know.

regards.

**Comment by vfoucault** [comment]
Well, There is multiple choices here. Since we deploy one product with many features that shares some common variables, it make sens to group them in the same ansible Role. It could be also done with multiple roles but in separated git repos, as it is not easy for people willing to use your code to automate things with a git repo containing multiple roles. 

Also, having 1 ansible role just to perform the CP installation, another one for broker stuff... it's huge and overkill. Based on one single role, you may setup your env as per you needs. If you do not need schema registry, up to you to not set it up by not adding the `confluent_roles: ['schema-registry']` to any ansible group you may have.

As per your remark, it is fairly easy to group roles by hosts group. Let's says that your deployement scenario would be Three machines for zk, kafka, and schema registry, just specify the following : 

```yaml
confluent_roles:
    - zookeeper
    - kafka-broker
    - schema-registry
```

All these roles will be applied in sequence, as SR requires kafka which itself requires zk.
If you have 3 sepearated set of hosts for the CP: 

group "zookeepers" -> confluent_role: ['zookeeper']
group "bokers" -> confluent_role: ['kafka-broker']
group "schema" -> confluent_role: ['schema-registry']

and so on.

**Comment by cotedm** [comment]
@vfoucault I think there is some confusion about what we're deploying here. It's not one product with multiple features. The Confluent Platform is many products that work together, but they are logically separate services. I'm not sure what the problem is with multiple roles in the same github repo. This seems to be common practice. A few examples from similar situations:
https://github.com/ansible/ansible-examples/tree/master/mongodb
https://github.com/ansible/ansible-examples/tree/master/wordpress-nginx
https://github.com/cloudera/cloudera-playbook
https://github.com/hortonworks/ansible-hortonworks

I agree that there is some refactoring to make the installation more efficient and we can be more targeted with the installs, but this seems like premature optimization given the high value of the other pull requests you've been making that depend on this one. I do not agree that we should restructure the repository this way without seeing some evidence that this is done elsewhere but even then I'm not sure it makes sense. However, I really do like the ideas from the other pull requests but we're blocked because this is the base for all of the other ones. Can you possibly rebase the other pull requests on master so we can make progress there instead? I think there's a lot of value that way.

**Comment by vfoucault** [comment]
It is easy to manage multiple role within a same folder for one project requiring to deploy some component. But juste imagine how will i integrate this in our deployment scenario, that is quite common. I have the same thing, one repo with our custom roles inside, and some ansible galaxy/github requirements that will be fetched and places inside the role folder.

I'm starting to think that your roles are made only for demo purposes, showing people that they could easily integrate the CP within their infrastructure.
I wished that I could contribute more this this tool, because I do like what you guys are doing. Event if it is not yet perfect and that there still room for improvement, i do not really have more time for this. As it is, it's working for my scenario.

So I will stick on this, on my side, improving it steps by step.

regards.

**Comment by cotedm** [comment]
Thanks for letting me know @vfoucault. I appreciate the discussion, good luck with your deployment!

**Pull request closed without merging**
