### PR TITLE
Refactor; Make ordered restart logic reusable for other tasks

### PR DESCRIPTION
**Pull request by erikgb**
# Description

We wanted to add system update to our Kafka Ansible play. To avoid unnecessary downtime on the cluster, we found the logic in ordered_restart.yml of Zookeeper and Kafka Broker very appealing. At the moment we have implemented the system update by copy-modifying the content of the two ordered_restart.yml files in confluent.zookeeper and confluent.kafka_broker roles.

This PR extracts the ordering logic implemented for restart into a potentially reusable task file (ordered_action.yml). This change will allow us (and others) to reuse the smart ordered logic without copy-modify.

PS: I can refactor the PR to exactly two commits - to avoid the currently technical big diff. The actual diff is quite smaller. Please advice!

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

The exact same setup is used to perform system update on our cluster - including restart of host after package updates installed.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] Any variable changes have been validated to be backwards compatible

### CODE REVIEW

**Comment by JumaX** [comment]
@erikgb Thanks for the work on this!  We currently do not support updating components via these playbooks, as there is actually a fair bit of testing and validation that needs to happen for this to be successful.  It isn't quite as simple as just having the rolling logic, or we would have included this already.  In fact that logic you have discovered, was my colleague @domenicbove investigations into this.

He's currently working on this now and we are looking at including it in a future release.  I will leave it to him to comment on where he is at with his work and if this PR can be factored into this or not.

If this work can be factored in, two things jump out at me:

1. The PR needs to be rebased to 6.1.x, as we don't include new functionality changes in older releases, we only include bug fixes.

2. The Checks of the PR have failed due to the following linting errors, so they will need to be corrected:

 yamllint -c ../../.yamllint ../..[0m
16:44:00  ../../roles/confluent.zookeeper/tasks/ordered_restart.yml
16:44:00    5:38      error    no new line character at the end of file  (new-line-at-end-of-file)
16:44:00  
16:44:00  ../../roles/confluent.kafka_broker/tasks/ordered_restart.yml
16:44:00    5:38      error    no new line character at the end of file  (new-line-at-end-of-file)

**Comment by erikgb** [comment]
@JumaX Thanks a lot for the input on the failing yamllint! Such a minor error breaking things up. 😄 I am a big fan of linting, but it would be nice to get the feedback from the CI-build.

I will re-target the PR for the 6.1.x branch, and await the comments from @domenicbove. The ordered logic is super-smart! Serial, without using Ansible serial (the hammer). Kudos!

**Comment by domenicbove** [comment]
@erikgb So in an effort to support rolling reconfiguration, I realized there is a problem with how the current handlers do rolling restarts. The way it works now is:

All hosts get reconfigured, and the the restart happens one at a time. The issue with this is: if the reconfiguration was invalid. it would be better to reconfigure one, restart it, and _if that host fails to start_, then the other remaining hosts have will stay in their old functioning configuration.

Now I am in the process of changing this logic to be one at a time in a new PR. Take a look at the new kafka playbook:
https://github.com/confluentinc/cp-ansible/pull/487/files#diff-47198b7e656f6799d365a69eba41aedc6509d00cc41d5618132f646e7b43faa7

This removes all the ordered restart logic from the role handlers, and puts it into a playbook so that the roles are simpler.

I think your goal is to make the ordered restart logic extendable, and that is a fair request. So can you take a look at that pr and give your input. My guess is you want a way to replace the role that gets run with one of your own.

**Comment by erikgb** [comment]
@domenicbove Thanks for getting back to me! You are absolutely right - I want to reuse the ordered restart logic to perform another task: host system update. And that may require a reboot of the host. In order to avoid unnecessary downtime on the cluster, we would like to do that serially - one host at a time.

And we also learned (the hard way), that the logic does not seem to handle errors properly. Somehow it seems that all host in one of our DEV clusters had some misconfiguration which resulted in failed reboot after patching (missing disk), and that was applied to all hosts in the cluster before the play failed with error. 😉 Whooops - cluster gone!

I had a quick look at your WIP PR, and it seems like you are into something! Do you want me to comment "over there"? My main concern is that your proposed changes will make the play considerable slower, but there might be few options to avoid that?

I'll guess I will close this PR - since you are working on a major rewrite of this.

**Comment by domenicbove** [comment]
@erikgb Yes please move the comments over to the other PR. My plan is to move forward with that one.

Regarding the speed of things, there is a variable: kafka_broker_reconfiguration_pattern which you can set to parallel to speed things up, but you'll lose the serial restart capability. It's worth considering if there are still downsides to the new approach, please LMK!

**Comment by domenicbove** [comment]
@erikgb Please review this PR: https://github.com/confluentinc/cp-ansible/pull/487 This is the direction we are going in our upcoming 6.1.0 release/ forward. With that said, I think this one can be closed, but I hope the work done there can be extended to your use case

**Pull request closed without merging**
