### PR TITLE
Update DEVELOPMENT_GUIDE.md

### PR DESCRIPTION
**Pull request by ldom**
typo

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

**Test Configuration**:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] Any variable changes have been validated to be backwards compatible

### CODE REVIEW

**Comment by domenicbove** [comment]
Can we actually target 6.1.x for this one? nice catch though!

**Comment by ldom** [comment]
> Can we actually target 6.1.x for this one? nice catch though!

I didn't find that document in the 6.1 branch. Am I missing something?

**Comment by domenicbove** [comment]
So `6.1.1-post` doesn't have the dev guide yet bc 6.1.x got the dev guide after 6.1.1-post was cut. When 6.1.2-post gets cut from 6.1.x youll see it. Anyhow target 6.1.x and we will make sure it gets into 6.2.x and all releases. 

Documented here: https://github.com/confluentinc/cp-ansible/blob/6.2.x/DEVELOPMENT_GUIDE.md#branching-model

I tried updating the branch, but it didn't work

**Review by domenicbove — APPROVED** [review]
Thanks

**Pull request merged**
