### PR TITLE
Feature : Support debian buster

### PR DESCRIPTION
**Pull request by LGouellec**
# Description

This PR allow to support Debian 10 Buster.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Tested with Azure VM Debian 10 Buster.

**Test Configuration**:

# Checklist:

- [X] My code follows the style guidelines of this project
- [ X I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] Any variable changes have been validated to be backwards compatible

### CODE REVIEW

**Comment by domenicbove** [comment]
It appears you mean to merge this into 6.1.x not 6.0.1-post. Is that correct? Can you change it?

**Comment by JumaX** [comment]
@LGouellec @domenicbove we don't support Debian Buster as a platform currently.  Reaching out internally to see what the best way forward is for this work.  Will follow up once we have more details.

https://docs.confluent.io/platform/current/installation/system-requirements.html

**Comment by LGouellec** [comment]
> It appears you mean to merge this into 6.1.x not 6.0.1-post. Is that correct? Can you change it?

Yeah, this an error. I change target branch soon.

**Review by JumaX — APPROVED** [review]
LGTM.

**Review by domenicbove — APPROVED** [review]
LGTM

**Comment by JumaX** [comment]
@LGouellec Thanks for the work on this.  We are going to merge this in, however it still falls outside of Confluent Support, until such time as our official docs are updated to show that this platform is supported.

https://docs.confluent.io/platform/current/installation/system-requirements.html

**Pull request merged**
