### PR TITLE
Zookeeper chroot capability

### PR DESCRIPTION
**Pull request by domenicbove**
# Description

Adds a variable for zk chroot: `zookeeper_chroot`
Must update the sasl scram creation bash commands with this variable

Fixes # (https://github.com/confluentinc/cp-ansible/issues/691)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

update zookeeper-mtls

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] Any variable changes have been validated to be backwards compatible

### CODE REVIEW

**Review by a-narenji — APPROVED** [review]
We checked it in our test environment.
It worked great.
Many thanks for adding this feature.

**Review by gitfrog0 — APPROVED** [review]
Looks good, tested locally.

**Comment by gitfrog0** [comment]
Err, just found an issue.  Occurs when using a rolling deployment to update an existing cluster.
In dynamic_groups.yml, the Get Controller Broker ID task needs the chroot in the zookeeper-shell connection. 
{{ binary_base_path }}/bin/zookeeper-shell {{ groups['zookeeper'][0] }}:{{ zookeeper_client_port }}{{zookeeper_chroot}}

**Comment by domenicbove** [comment]
arg yep thats a bug! wish we caught that before the latest release

**Pull request merged**
