### PR TITLE
Missing zk fips properties

### PR DESCRIPTION
**Pull request by domenicbove**
# Description

On fips enabled hosts need these properties for zk tls to work

Fixes # (issue)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Properties validated by customer

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] Any variable changes have been validated to be backwards compatible

### CODE REVIEW

**Comment by prestonmcgowan** [comment]
This looks like it would pass for the algorithm issues, but more work needs to be done for the keystores with the keytool and openssl playbooks

**Comment by prestonmcgowan** [comment]
Based on the conversation, i think these need to be added to the other components too.

**Comment by domenicbove** [comment]
@prestonmcgowan what work specifically? 

And all the other components have the pkix properties set, its just zk thats missing this.

**Review by JumaX — APPROVED** [review]
LGTM.

**Pull request merged**
