### PR TITLE
Added filters to help with generating properties and ini files. #60.

### PR DESCRIPTION
**Pull request by jcustenborder**
Added filters for working with hosts.

### CODE REVIEW

**Comment by cotedm** [comment]
Found a couple of other roles that need updates:
control center
tools

For some reason connect is also not integrated properly with control center either. I'll investigate this next. If you can update the ``tasks/main.yml`` for schema registry, control center, and tools and I figure out what's going on with control center/connect integration, everything else seems to be working.

**Comment by jcustenborder** [comment]
@cotedm I've got this cleaned up. I did need to make one breaking change. Basically I cannot build `kafka.broker.config` including anything from `kafka.broker` so I had to change `kafka.broker.id` to `config.broker.id`. Other than that everything else stays the same.   I think this strategy could make #53 much easier.

**Comment by cricket007** [comment]
> cannot build kafka.broker.config including anything from kafka.broker

Was having similar issues when trying solutions to #45 . At first glance, the config re-org here might help there.

**Comment by cricket007** [comment]
Anything left that is blocking this?

**Comment by JumaX** [comment]
@jcustenborder @cotedm Any update on this?  If not, I recommend we close this out, as its quite old and much has changed since this PR was filed.

**Pull request closed without merging**
