### PR TITLE
Adding CI system for running lint and sanity checks

### PR DESCRIPTION
**Pull request by rrbadiani**
# Description

Adding CI system for running lint and sanity checks. 
- It builds ansible collection
- Runs galaxy importer test
- Runs ansible-test sanity
- Runs  these tests for ansible version 9 and python versions (3.10, 3.11, 3.12)

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

# Checklist:

- [ ] Any variable/code changes have been validated to be backwards compatible (doesn't break upgrade)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If required, I have ensured the changes can be discovered by cp-ansible discovery codebase
- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by mansisinha** [comment]
will these tests be mandatory for merging a PR?

**Comment by rrbadiani** [comment]
> will these tests be mandatory for merging a PR?

No we can make them mandatory from github settings but i dont think they will be mandatory to merge the pr

**Comment by mansisinha** [comment]
> > will these tests be mandatory for merging a PR?
> 
> No we can make them mandatory from github settings but i dont think they will be mandatory by default to merge the pr

so when exactly will this be triggered? in the current PR, I don't see the ci system triggered? shouldn't it automatically be triggered with every PR?

**Comment by rrbadiani** [comment]
> so when exactly will this be triggered? in the current PR, I don't see the ci system triggered? shouldn't it automatically be triggered with every PR?

once this pr is merged and we run cc-service bot it will generate a project.yml file. after that for all prs this pipeline will run

**Comment by mansisinha** [comment]
> > so when exactly will this be triggered? in the current PR, I don't see the ci system triggered? shouldn't it automatically be triggered with every PR?
> 
> once this pr is merged and we run cc-service bot it will generate a project.yml file. after that for all prs this pipeline will run

how have we tested the changes?

**Comment by rrbadiani** [comment]
> > > so when exactly will this be triggered? in the current PR, I don't see the ci system triggered? shouldn't it automatically be triggered with every PR?
> > 
> > 
> > once this pr is merged and we run cc-service bot it will generate a project.yml file. after that for all prs this pipeline will run
> 
> how have we tested the changes?

Something similar I have tested on cp-ansible-test repo. But it isnt exactly same. It has more versions of ansible where this kind of test is happening. It also needs to run on demand whereas this will run on PRs & branch creation.

**Review by mansisinha — APPROVED** [review]

**Pull request merged**
