### PR TITLE
Master add confluent namespace to roles

### PR DESCRIPTION
**Pull request by hedinfaok**
Adds the `confluent.` namespace to the roles, so that they can be used in other playbooks.

### CODE REVIEW

**Comment by cotedm** [comment]
@hedinfaok this seems like a good idea. Is this common practice? I haven't seen it done before.

**Comment by hedinfaok** [comment]
Well, I was trying to re-use these roles in our reference architecture, and I ran into the namespace issue.  Since these roles are already public, it would be helpful if they were in separate repos and published to ansible-galaxy. In that case, prepending the roles with `confluent.` would make a lot of sense. 

http://docs.ansible.com/ansible/latest/reference_appendices/galaxy.html

Right now, I have a playbook that pulls my fork of this repo and moves the roles into our project, but it _would_ be a lot easier if I could use `ansible-galaxy install confluent.kafka-broker` :)

I didn't see any `CONTRIB` docs, so I did the PR just to share with your team. Thanks for making Ansible scripts for the product, so I could have a reference 👍

**Comment by cotedm** [comment]
I agree that would be a lot easier! Would you mind updating the example `all.yml` with the namespace updates? Then I think we're good to merge. I'll look into what we have to do to get this up on galaxy.

**Comment by hedinfaok** [comment]
@cotedm Ready for review

**Comment by cotedm** [comment]
LGTM, merging, thanks!

**Pull request merged**
