### PR TITLE
60 colocated upgrade bugfix

### PR DESCRIPTION
**Pull request by domenicbove**
# Description

Adds logic to the upgrade_kafka_broker.yml playbook to handle colocated zk and kafka, which when you upgrade in that configuration the kafka package will be upgraded during the zk upgrade and in the case of confluent-kafka-2.12, the package even switches names.

Fixes # (https://github.com/confluentinc/cp-ansible/issues/423)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Manually tested plaintext 3 node zk colocated w 3 node kafka upgrade
Both confluent_server_enabled: true/false

Ran the install, zk upgrade and kafka upgrade

# Checklist:

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] Any variable changes have been validated to be backwards compatible

### CODE REVIEW

**Review by JumaX — APPROVED** [review]
LGTM.

**Comment by aglahe** [comment]
FYI...you may need to revisit upgrade_zookeeper.yml, since it's checking for the confluent_common-2.12...if that for somereason doesn't exist...it fails

**Review by JumaX — CHANGES_REQUESTED** [review]
@domenicbove Can you clarify this further?  I believe what you are saying is that even with the package name change in 6.0.0 we will handle that gracefully.  However if you have co-located components, you still have the same problem of packages being upgraded while another service is running, correct?

**Comment by aglahe** [comment]
Basically, if you run upgrade_zookeeper.yml, and it get's through the section of removing confluent_common-2.12..and if you rerun upgrade_zookeeper.yml it will fail because it can't remove the already removed JARs.  I guess I would it expect to not error out in that condition because it can't find those packages....it should just continue the upgrade as normal.

**Comment by domenicbove** [comment]
@aglahe @JumaX I can confirm running the upgrade_zookeeper.yml in this branch twice does error out. I'll see what I can do!

**Comment by domenicbove** [comment]
Ok @aglahe @JumaX I just tested running zk and kafka upgrades twice w this branch, no errors. Can you please review this pr?

**Review by JumaX — APPROVED** [review]
LGTM.

**Pull request merged**
