### PR TITLE
Create new linting GH workflow from scratch

### PR DESCRIPTION
**Pull request by erikgb**
# Description

Related PR https://github.com/confluentinc/cp-ansible/pull/628. The available GHA seems a bit "immature", so I just created two custom jobs using two of the excellent [awesome-ci images](https://github.com/topics/awesome-ci).

I added two deliberate errors, to see how it looks like. These should ofc be reverted before merge.

Also fixed an innocent warning in a meta-file, to be able to remove that particualar rule from the skip-list.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] Any variable changes have been validated to be backwards compatible

### CODE REVIEW

**Comment by domenicbove** [comment]
Pretty cool failing tests there! I like this!

**Comment by erikgb** [comment]
> Pretty cool failing tests there! I like this!

Yes, me too. :-) Should I clean up and prepare for merge?

**Comment by domenicbove** [comment]
Yes, I'll approve when builds succeed!

**Review by domenicbove — APPROVED** [review]
LGTM

**Pull request merged**
