### PR TITLE
🐛 convert AnsibleVaultEncryptedUnicode to String in filter plugin #637

### LINKED ISSUE #637: Exception SASL SCRAM User when password is vaulted
**Describe the issue**

Using your playbook with sasl_protocol to scram. If you set user password vaulted, you have an exception in this [task](https://github.com/confluentinc/cp-ansible/blob/e7523d5011dc40a62c62ab3f1dcb78132f90c0a4/roles/confluent.kafka_broker/tasks/main.yml#L124) :
fatal: [XXXXXXX]: FAILED! => {"msg": "An unhandled exception occurred while templating '{{ kafka_broker_combined_properties | combine(kafka_broker_custom_properties) }}'. [....] can only concatenate str (not \"AnsibleVaultEncryptedUnicode\") to str"}

I think problem raise from combine_properties function because in default configuration password is string. So if password is vault encode myabe fix it with 'toString() python method' :
``` python

    def combine_properties(self, properties_dict):
        # Loops over master properties dictionary and combines sub elements if enabled
        final_dict = {}
        for prop in properties_dict:
            if properties_dict[prop].get('enabled'):
                final_dict.update(properties_dict[prop].get('properties'))
        return final_dict
```

**To Reproduce**
All Vars Configuration :
``` yaml
    sasl_protocol: scram

    sasl_scram_users:
      admin:
        principal: "admin"
        password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          32313537636131333038303532613231653233343565303831396530393061643031303432303632
          6537306234393563343861643834336430353930643062370a663563376131653664653430363963
          62303339313937646635663032326266383439623736623462373632313934643261303634663732
          3331643634623337610a616365613231346630656564616265656231633238313932333437363461
          65626165666531656463353562323165376135653631316435653337366164653063
      client:
        principal: "client"
        password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35653666663833386164616630353966363231633234633561663464653931393835653830303630
          3263373337396137653637383332656539373766346438370a353164383737306535646234363065
          66643863353439663064346564333062373265653036646137306531353336323931653931363032
          3231373831366531640a323161386538333966646635353462623263346234306631383635646237
          34613764663736346362616562623061333438613461616162386532373266393166

```

**Workaround**

A [workaround exist](https://github.com/ansible/ansible/issues/33067), you need to convert vault encoded string : 
``` yaml
    sasl_protocol: scram

    sasl_admin_password: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      32313537636131333038303532613231653233343565303831396530393061643031303432303632
      6537306234393563343861643834336430353930643062370a663563376131653664653430363963
      62303339313937646635663032326266383439623736623462373632313934643261303634663732
      3331643634623337610a616365613231346630656564616265656231633238313932333437363461
      65626165666531656463353562323165376135653631316435653337366164653063
      
    sasl_client_password: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      35653666663833386164616630353966363231633234633561663464653931393835653830303630
      3263373337396137653637383332656539373766346438370a353164383737306535646234363065
      66643863353439663064346564333062373265653036646137306531353336323931653931363032
      3231373831366531640a323161386538333966646635353462623263346234306631383635646237
      34613764663736346362616562623061333438613461616162386532373266393166

    sasl_scram_users:
      admin:
        principal: "admin"
        password: "{{sasl_admin_password|string}}"
      client:
        principal: "client"
        password: "{{sasl_client_password|string}}"
```

### PR DESCRIPTION
**Pull request by LGouellec**
# Description

Convert all password in inventory to string format. Also in case of developer injects value vaulted, filter_plugin convert AnsibleVaultEncryptedUnicode  to String format, and all works !

Fixes #637 

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- Create an inventory with Scram User configuration
- Vault password of user (admin & client of example below)
``` yaml
all:
  vars:
    # [....]

    #### SASL Authentication Configuration ####
    sasl_protocol: scram

    sasl_scram_users:
      admin:
        principal: "admin"
        password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          32313537636131333038303532613231653233343565303831396530393061643031303432303632
          6537306234393563343861643834336430353930643062370a663563376131653664653430363963
          62303339313937646635663032326266383439623736623462373632313934643261303634663732
          3331643634623337610a616365613231346630656564616265656231633238313932333437363461
          65626165666531656463353562323165376135653631316435653337366164653063
      client:
        principal: "client"
        password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35653666663833386164616630353966363231633234633561663464653931393835653830303630
          3263373337396137653637383332656539373766346438370a353164383737306535646234363065
          66643863353439663064346564333062373265653036646137306531353336323931653931363032
          3231373831366531640a323161386538333966646635353462623263346234306631383635646237
          34613764663736346362616562623061333438613461616162386532373266393166

# [...]
```
- Start ansible playbook **all.yml**

**Test Configuration**:

- Debian Buster VM (same machine for Broker & Zk)

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] Any variable changes have been validated to be backwards compatible

### CODE REVIEW

**Comment by domenicbove** [comment]
@LGouellec Nice work on this PR. Two things:

1. Can you target the 6.1.x branch? We recently added a dev guide w branching model to explain: https://github.com/confluentinc/cp-ansible/blob/6.1.x/DEVELOPMENT_GUIDE.md#branching-model

2. I'm wondering if we can "catch the vaulted password sooner". In the 6.1.x branch there is:
```
### Dictionary containing additional sasl scram users to be created during provisioning.
sasl_scram_users: {}

sasl_scram_users_final: "{{ _sasl_scram_users | combine(sasl_scram_users, recursive=True) }}"
```
And later the `sasl_scram_users_final` dict gets used everywhere, so its right then that we should make sure everything is a string. WDYT? We may need a new custom filter, but thats fine.

**Comment by LGouellec** [comment]
@domenicbove
Thanks for your feedbacks. I'll rework this PR ASAP.

**Comment by JumaX** [comment]
@LGouellec Thanks for this contribution, really great work!.  Can you point this to the 6.1.x branch?  If so, I can see about getting this merged today.

**Comment by JumaX** [comment]
@LGouellec I've changed the branch to 6.1.x and corrected a conflict.  Checks are running now, will do a final review and hopefully get this merged today.  Let me know if you have any questions.

**Comment by JumaX** [comment]
@LGouellec I may also branch off of this and submit a new PR with a test included.  Right now we do not test with vault at all, and it would be good to have the included in our molecule scenarios.

**Review by JumaX — APPROVED** [review]
LGTM.

**Comment by LGouellec** [comment]
> @LGouellec I've changed the branch to 6.1.x and corrected a conflict.  Checks are running now, will do a final review and hopefully get this merged today.  Let me know if you have any questions.

Thanks for your work. Happy to see this MR merged !

**Pull request merged**
