### PR TITLE
Add Yaml-linting 

### LINKED ISSUE #237: Yamllint and ansible-lint
First of all - thanks for creating those playbooks and roles. They are very helpful!
I am using ansible for a lot of my customers and I follow a rather strict linting policy and have some "errors" from this repository in that terms.
I was wondering if the maintainers of this repository would care about some "improvements" in terms of yamllint and ansible-lint?

### PR DESCRIPTION
**Pull request by Fobhep**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #237 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
1. Install yamllint >= 1.20.0
2. From the root dir
```
yamllint . 
```

**Test Configuration**:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Fobhep** [comment]
@domenicbove so this is my draft for yaml-linting. I guess it makes maybe more sense to add that and ansible-linting in two separate PRs.

The rules for yamlling are defined in .yamllint
I use the 1.20.0 Version.
The rule set is definitely open for discussion ;)

Maybe it makes also sense to add travis and run the yamllint there, or in your Jenkins pipeline.

**Comment by domenicbove** [comment]
@Fobhep Very cool! wondering do we need both yaml lint and ansible-lint?

**Comment by Fobhep** [comment]
@domenicbove imho there's no harm in doing additional `ansible-lint`.
`yamllint` is purely checking syntax, whereas `ansible-lint` does also checks upon deprecation and ansible [best pratices](https://docs.ansible.com/ansible-lint/rules/default_rules.html).

**Comment by domenicbove** [comment]
@Fobhep ok roger that. I want to confirm that ansible-lint can't just do it all. And wrt timing of this, I have a PR thats merging everything in 5.4.x back into 5.3.x branches (that can be brought back): https://github.com/confluentinc/cp-ansible/pull/232

and this is definitely something I'd like included. With that said, I'd either like this PR to be into the domenicbove:530-merge or to wait until that PR goes through and then merge into confluentinc:5.3.0-post branch

**Comment by Fobhep** [comment]
@domenicbove I am fine either way. 
Maybe two points to consider:
- Do you want to include the tests into some test-pipeline to make sure code of new contributors is in accordance?

- What is the timeline for #232 ? If you are quicker merging that without this merging this PR first and rebasing afterwards - maybe merge #232 first.
I have no pain with rebasing this PR lateron ;)

Ultimately your call :)

**Comment by Fobhep** [comment]
ping @domenicbove :) any updates on this?

**Comment by domenicbove** [comment]
Hey @Fobhep bare with us for a week or so. We are heads down working on this feature right now: https://github.com/confluentinc/cp-ansible/pull/246

Sorry for the delay!

**Comment by Fobhep** [comment]
@domenicbove no worries! just ping me when you have time :)

**Comment by domenicbove** [comment]
@Fobhep we finally released 5.5.0! Meaning we can get to this next
Question- which branch would you like support for yaml linting to start in? We have a tool that merges our code up thru branches.

I would prefer just to get it into the 5.5.0-post branch and then we would have yaml linting starting in 550 and higher. If you prefer it in the 5.4.x branches can you change this pr to merge into 5.4.0-post (not 5.4.1-post)?

**Comment by Fobhep** [comment]
@domenicbove sure - 5.5.0 sounds good to me - then I will rebase it to 5.5.0-post and ping you once I am done :)

**Comment by Fobhep** [comment]
@domenicbove so I rebased it now.

Should I add a Jenkins job to run the actual linting?

**Comment by domenicbove** [comment]
@Fobhep Ideally this integrates with molecule, which has a stage for linting. I will investigate now. But ya we already have jenkins running molecule tests, molecule can also test our linting... so voila it should all work! 

Have you tried out the molecule yet? we need to document it. I think the commands are 
```
pip install molecule docker
# start docker, give it a lot of resources under preferences
cd roles/confluent.test
molecule converge -s plain-rhel
molecule verify -s plain-rhel
molecule destroy -s plain-rhel
```

where plain-rhel is one of our many deployment scenarios

**Comment by domenicbove** [comment]
Hey I just made a pr into your linting branch: https://github.com/ATIX-AG/cp-ansible/pull/1

I suppose we could merge yours first and then go with that one, but i wanted your review

**Comment by Fobhep** [comment]
@domenicbove awesome - thanks for your PR. Looks good so far I took a quick glance only, but I will check it still today. I would merge it then first and then we can merge the whole thing here.

**Comment by domenicbove** [comment]
@Fobhep can you merge in the latest 5.5.0-post into your branch? looks like there are merge conflicts

**Comment by Fobhep** [comment]
@domenicbove just did a rebase on 5.5.0-post

**Comment by Fobhep** [comment]
seems to have a build error still - sadly I cannot see the Jenkins details

**Comment by domenicbove** [comment]
You *should* be able to see the logs by clicking the Details link. I just checked the logs and the linting errored out

**Comment by Fobhep** [comment]
Yeah I tried that but I get this:

image

**Comment by Fobhep** [comment]
@domenicbove mh I remove OAUTH for Jenknins and retried it but I still cannot check the Jenkins results :thinking: 
anyhow the rest is fine now :)

**Pull request merged**
