### PR TITLE
(chore) cp-ansible: add retries to all RBAC rolebinding creation (7.0.x)

### PR DESCRIPTION
**Pull request by justinrlee**
# Description

Sometimes MDS takes a little bit of time to settle; this adds retries to various API calls that may be made while it's still settling.  Note that the MDS healthcheck doesn't appear to be sufficient.

Fixes # (issue)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

Tested in a customer environment.

**Test Configuration**:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] Any variable changes have been validated to be backwards compatible

### CODE REVIEW

**Comment by justinrlee** [comment]
(Re-creation of this PR: https://github.com/confluentinc/cp-ansible/pull/1006).  Three comments:

Note that these create queries always return 204, not 200: https://docs.confluent.io/platform/current/security/rbac/mds-api.html#post--security-1.0-principals-principal-roles-roleName; so it should be safe to remove the 200.

Also note - I'm not sure if I need different variables for each task. I don't believe I do (they're just used for the individual task completion and should be safely overwrite-able, but something to be validated by somebody who knows Ansible better than I do.

Also, I fixed a spacing issue in one of the tasks.

**Comment by justinrlee** [comment]
cc @utkarsh5474.  Thanks for your help with this!

**Review by nsharma-git — APPROVED** [review]

**Comment by justinrlee** [comment]
Hey, question on this - aside from this PR, do I need PRs for other branches?

**Comment by nsharma-git** [comment]
> Hey, question on this - aside from this PR, do I need PRs for other branches?

This PR will go in 7.0.x and all downstream branches!

**Pull request merged**
