### PR TITLE
Include new version file config prometheus

### PR DESCRIPTION
**Pull request by alvarobacelar**
# Description

This PR include new yaml config prometheus that improve significantly the scraping time and get new metrics Apache Kafka's version 2.5 or higer. The image above show the improvement of scraping time:

image

Fixes # (n/a)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Ran molecule test which will validate all roles function

# Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] Any variable changes have been validated to be backwards compatible

### CODE REVIEW

**Review by erikgb — CHANGES_REQUESTED** [review]
Please do not reformat the yaml as part of this PR. It makes it harder to review.

**Comment by alvarobacelar** [comment]
Ok. I'll change it.

**Comment by JumaX** [comment]
@erikgb @alvarobacelar A colleague has updated this work further on the following PR, to gather all metrics but still keep the performance enhancements.  I've added you both as reviewers:

https://github.com/confluentinc/cp-ansible/pull/747

**Comment by nsharma-git** [comment]
Hello @alvarobacelar, Please let us know if you agree with @JumaX recommendation. If thats not the case, can you please resolve the conflicts and let us know whats the extra metrics we are collection in this PR. 
Thanks!

**Comment by nsharma-git** [comment]
Closing in favour of https://github.com/confluentinc/cp-ansible/pull/747. Let me know if you have different opinion. 
Thanks !

**Pull request closed without merging**
