### PR TITLE
Fix ansible sanity tests - add to ignores list

### PR DESCRIPTION
**Pull request by wadhwa1**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

**Test Configuration**:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] Any variable changes have been validated to be backwards compatible

### CODE REVIEW

**Review by utkarsh5474 — APPROVED** [review]
Is this in addition to the fix @mansisinha made? Or, is this exclusive to that? Let's keep one of these patterns to ignore specific sanity tests

**Comment by utkarsh5474** [comment]
Also, did we try skipping on folder level? Does that work

**Comment by mansisinha** [comment]
> Is this in addition to the fix @mansisinha made? Or, is this exclusive to that? Let's keep one of these patterns to ignore specific sanity tests

this is exclusive to that, we are trying to figure which would be a better approach?

**Review by mansisinha — APPROVED** [review]
lgtm

**Comment by wadhwa1** [comment]
> Is this in addition to the fix @mansisinha made? Or, is this exclusive to that? Let's keep one of these patterns to ignore specific sanity tests

Thanks @utkarsh5474 for review, we discussed internally with team and went ahead with same ignore.txt (existing ones) instead of skipping each py file.
and anyways this is temporary workaround till we fix our python files for linting/ sanity issues

**Comment by wadhwa1** [comment]
> Also, did we try skipping on folder level? Does that work

Yeah, I tried that, but sanity check failed for ignore file itself :D, so I believe that isn't easy to configure

**Pull request merged**
