### PR TITLE
Read packages/version from env vars - 6.1.x

### PR DESCRIPTION
**Pull request by utkarsh5474**
# Description

Extension of https://github.com/confluentinc/cp-ansible/pull/918 for 6.1.x

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Tested as part of 918

**Test Configuration**:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] Any variable changes have been validated to be backwards compatible

### CODE REVIEW

**Comment by utkarsh5474** [comment]
Bumping this up, @confluentinc/cp-ansible-dev 
It's pretty much similar to #940 #938

**Review by JumaX — APPROVED** [review]
LGTM.

**Comment by nsharma-git** [comment]
I was hoping you will do pint merge as we don’t have version specific logic. 
You may get conflicts in this process, but it would have helped in your future changes. 



  <https://www.confluent.io/>	
Neeraj Sharma 
Staff Engineer 
+91 8197088222 <tel:+91 8197088222> 
Follow us:  <https://www.confluent.io/blog?utm_source=footer&utm_medium=email&utm_campaign=ch.email-signature_type.community_content.blog> <https://twitter.com/ConfluentInc> <https://www.linkedin.com/company/confluent/> <https://slackpass.io/confluentcommunity> <https://youtube.com/confluent>

**Comment by utkarsh5474** [comment]
I'd pint merge with strategy ours to this branch only. 

I thought about pint merge to downstream @nsharma-git 
But there were two issues to this: 
7.0.x branches have new dockerfiles. So, I'd have to create a new PR for them either way.
Also, 6xy branches use a diff path to grab the default confluent_package_version. So, this was required to be merged only in 6xy related dev branches and not 7xy
Does pint have any such feature to control the exact downstream branches used?

**Pull request merged**
