### PR TITLE
Use list in all yum/apt package install tasks

### PR DESCRIPTION
**Pull request by erikgb**
# Description

This PR replaces all loops on package install tasks with a list of packages supplied to the `yum` and `apt` ansible modules. This should improve performance on the desired state package tasks.

I have left out the upgrade-playbooks, at least for now, as they are not idempotent (#https://github.com/confluentinc/cp-ansible/issues/588) and will typically be run just once.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] Any variable changes have been validated to be backwards compatible

### CODE REVIEW

**Review by domenicbove — APPROVED** [review]
I like it! The one thing I need to test is to confirm if you install 6.1.0, no 6.1.1 packages get installed. Thanks for all the contributions!

**Comment by domenicbove** [comment]
Doing some testing now- looks like packages with the correct versions are getting installed:
```
dbove@dbove-MBP15 terraform % docker exec -it kafka-broker1 rpm -qa | grep confluent
confluent-telemetry-6.1.0-1.noarch
confluent-rest-utils-6.1.0-1.noarch
confluent-kafka-rest-6.1.0-1.noarch
confluent-ce-kafka-http-server-6.1.0-1.noarch
confluent-security-6.1.0-1.noarch
confluent-common-6.1.0-1.noarch
confluent-metadata-service-6.1.0-1.noarch
confluent-server-rest-6.1.0-1.noarch
confluent-server-6.1.0-1.noarch
confluent-rebalancer-6.1.0-1.noarch
```
I'm hoping not to see any 611 in this list fyi. 

It does seem to take a while now. where before at least you felt like there was progress bc of the loop. I can't say its faster or not but I'm guessing it is. We might be able to tell via old jenkins logs- ill check.

**Comment by domenicbove** [comment]
In you jenkins logs it appears to install the zookeeper packages it took ~40 seconds:
```
22:51:42      TASK [confluent.zookeeper : Install the Zookeeper Packages] ********************
22:52:21      changed: [zookeeper11]
22:52:21      changed: [zookeeper31]
22:52:21      changed: [zookeeper21]
```

From other logs without this change we have ~60 seconds:
```
08:52:12      TASK [confluent.zookeeper : Install the Zookeeper Packages] ********************
08:52:17      changed: [zookeeper21] => (item=confluent-common)
08:52:17      changed: [zookeeper11] => (item=confluent-common)
08:52:17      changed: [zookeeper31] => (item=confluent-common)
08:52:24      changed: [zookeeper11] => (item=confluent-rest-utils)
08:52:24      changed: [zookeeper21] => (item=confluent-rest-utils)
08:52:24      changed: [zookeeper31] => (item=confluent-rest-utils)
08:52:30      changed: [zookeeper21] => (item=confluent-metadata-service)
08:52:30      changed: [zookeeper11] => (item=confluent-metadata-service)
08:52:32      changed: [zookeeper31] => (item=confluent-metadata-service)
08:52:36      changed: [zookeeper11] => (item=confluent-ce-kafka-http-server)
08:52:36      changed: [zookeeper21] => (item=confluent-ce-kafka-http-server)
08:52:38      changed: [zookeeper31] => (item=confluent-ce-kafka-http-server)
08:52:46      changed: [zookeeper11] => (item=confluent-kafka-rest)
08:52:46      changed: [zookeeper21] => (item=confluent-kafka-rest)
08:52:46      changed: [zookeeper31] => (item=confluent-kafka-rest)
08:52:50      changed: [zookeeper21] => (item=confluent-server-rest)
08:52:50      changed: [zookeeper11] => (item=confluent-server-rest)
08:52:50      changed: [zookeeper31] => (item=confluent-server-rest)
08:52:54      changed: [zookeeper21] => (item=confluent-telemetry)
08:52:54      changed: [zookeeper11] => (item=confluent-telemetry)
08:52:55      changed: [zookeeper31] => (item=confluent-telemetry)
08:53:10      changed: [zookeeper21] => (item=confluent-server)
08:53:10      changed: [zookeeper31] => (item=confluent-server)
08:53:10      changed: [zookeeper11] => (item=confluent-server)
```

I just checked another log, also around 60 seconds. So theres definitely efficiency improvements! Nice work!

**Comment by erikgb** [comment]
Yes, it is sad that you don't see the progress - as you do with the loop. But speed is more important in my opinion. 😄

**Comment by domenicbove** [comment]
Yep this is a nice improvement. Thanks for yet another contribution! I just confirmed no 6.1.1 packages were installed on any hosts after setting confluent_package_version to 6.1.0

**Pull request merged**
