### PR TITLE
61x kafka connect replicator plain kerberos rhel

### PR DESCRIPTION
**Pull request by JumaX**
# Description

This PR updates the Kafka Connect Replicator Plain Kerberos RHEL scenario to properly run.  We needed to add additional properties for keystore and truststore passwords, remove rbac and ldap related properties as this scenario was introduced before RBAC support on replicator.

Fixes # (issue)

ansieng-985.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

This Kafka Connect Replicator Plain Kerberos RHEL scenario  now completes and the verification produces and consumes data while it is transferred between clusters via replicator.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] Any variable changes have been validated to be backwards compatible

### CODE REVIEW

**Review by nsharma-git — COMMENTED** [review]
Looks good to me. Thanks for taking care of this one. 
Do you want to update the variable doc for the changes in variable description ?

**Comment by JumaX** [comment]
Really good catch!  Re: variable doc.

**Comment by JumaX** [comment]
@nsharma-git looks like there were a few other variable changes from previous PR's which had also not been updated, so those are now in here as well.

**Comment by nsharma-git** [comment]
> @nsharma-git looks like there were a few other variable changes from previous PR's which had also not been updated, so those are now in here as well.

Thanks!

**Review by nsharma-git — COMMENTED** [review]
@JumaX Do you want to change the target to 6.0.x

**Comment by JumaX** [comment]
@nsharma-git this was built on 6.1.x, if we move it back to 6.0.x we end up with ALOT of changes that are not appropriate.  Will do a seperate PR for 6.0.x if you want this back ported there as well.

**Comment by JumaX** [comment]
@nsharma-git just confirmed, we didn't add support for replicator until 6.1 thus this scenario doesn't exist in 6.0.x, thus we are fine to merge this up.

**Review by nsharma-git — APPROVED** [review]

**Pull request merged**
