### PR TITLE
fix: add missing tags on new tasks

### PR DESCRIPTION
**Pull request by erikgb**
# Description

We are attempting to upgrade to CP 7.3.0 (cp-ansible 7.3.0-post branch), and experience a few issues. Last in line is:

````
TASK [confluent.platform.common : get key hash] ********************************
fatal: [REDACTED]: FAILED! => 
  msg: |-
    The task includes an option with an undefined variable. The error was: 'key_hash_remote' is undefined
  
    The error appears to be in '/home/ansible/.ansible/collections/ansible_collections/confluent/platform/roles/common/tasks/config_validations.yml': line 88, column 3, but may
    be elsewhere in the file depending on the exact syntax problem.
  
    The offending line appears to be:
  
  
    - name: get key hash
      ^ here
````

This seem to happen because we skip some non-working validations, at least in our environment, using Ansible tags:

````
ANSIBLE_SKIP_TAGS: "validate_ssl_keys_certs,validate_memory_usage,validate_ansi_version"
````

Most tasks in the `config_validations.yml` file seems to have tags that allow you to skip certain things. This PR adds the missing tags to new tasks added in CP 7.3.0.

~~Intentionally targeting the 7.3.0-post branch.~~

Fixes # (issue)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Verified fixing our issue running in check mode against our dev-cluster.

**Test Configuration**:

N/A

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] Any variable changes have been validated to be backwards compatible

### CODE REVIEW

**Review by anuj-apdev — COMMENTED** [review]
LGTM.

**Review by nsharma-git — COMMENTED** [review]
Thanks @erikgb . Can we merge these changes in 7.3.x ? We will have a new patch release in a few weeks.

**Comment by erikgb** [comment]
Well, we need all PRs in to be able to upgrade. I would prefer this to be fixed on the release branch, and I expect others to get issues as well. But we have been running against x-branches (and commit sha) before, so we will survive. 😁

**Comment by erikgb** [comment]
@nsharma-git Let me know what the team prefer. I think the issues might be blocking bugs for some users, but I have no problem updating the PR to target the 7.3.x branch.

**Comment by utkarsh5474** [comment]
Thanks Erik, thanks for the PR
If you have some time, can you check without skipping the tag `validate_ssl_keys_certs`?
We had a PR recently to fix issues with this validation. I reckon it might work for you now.

**Comment by erikgb** [comment]
> Thanks for the PR @erikgb If you have some time, can you check without skipping the tag `validate_ssl_keys_certs`? We had a PR recently to fix issues with this validation. I reckon it might work for you now.

@utkarsh5474 I just tested without skipping the cert/keys validations, and it seems to work better than it used to. We generally prefer to be able to skip these validations, as they historically tend to create issues for us - especially the validation of memory, which is just wrong IMO.

**Comment by erikgb** [comment]
@utkarsh5474 The CI build error seems highly unrelated. Is the 7.1.x branched borked?

**Review by utkarsh5474 — APPROVED** [review]

**Comment by nsharma-git** [comment]
We are going ahead with these changes as the CI error is a known issue and it's unrelated with this change.

**Pull request merged**
