### PR TITLE
set log4j root logger thru variable

### PR DESCRIPTION
**Pull request by piif**
# Description

Same as #598 for 6.1.0 branch

### CODE REVIEW

**Comment by domenicbove** [comment]
Hi @piif ! Thanks for all your interest/improvements! Please review https://github.com/confluentinc/cp-ansible/pull/572

Which I believe covers the work you just did. Also we try to make all of our PRs into .x branches (ie 6.1.x). I should add that into our contribution guide.

**Comment by piif** [comment]
Hi @domenicbove, #572 contains actually what I need and much more, thus it seems perfect as a replacement of mine !

I note for future contributions to work on `.x` branches instead of `-post` ones, thanks.

**Comment by domenicbove** [comment]
Yes sorry for the confusion. the `.x` branches are our "future release" branches, ie 6.0.x will become 6.0.3-post on our next release. It's our best way to keep things versioned. And we try to keep only minor features/ bugfixes on the 6.0.x and 6.1.x ... for major features those would go onto 6.2.x and get released with our next major version. 

I think this PR can be closed bc the logic is already committed to 6.1.x branch, wdyt?

**Comment by piif** [comment]
I agree, we can close.

Thank you for your help

**Pull request closed without merging**
