### PR TITLE
Refactor; Move tasks and filter_plugins into roles to make the roles more self-contained

### PR DESCRIPTION
**Pull request by erikgb**
# Description

Refactoring filter_plugins as discussed in https://github.com/confluentinc/cp-ansible/issues/113.

Relates to #113

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Refactoring, and I and hope any issues are picked up by the CI build.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] Any variable changes have been validated to be backwards compatible

### CODE REVIEW

**Comment by erikgb** [comment]
@domenicbove I think I need some assistance here. The build is failing, but I cannot see what the problem is. 😢 It is like programming blindfolded..... I made 2 commits first, just to check if my approach to the refactoring worked. And it did - green build! But after pushing the subsequent commits, the build is suddenly failing. I have looked through the commits again and again, but I cannot find the reason.... Please help!

**Comment by erikgb** [comment]
@domenicbove I have now pinned the problem down to what is currently the last commit; which involves moving the `failure_handling.yml` file into the role `confluent.common`. I thought it might be a problem with `include_role` vs. `import _role`, but apparently no. It is currently using the almost deprecated [include module](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/include_module.html), and I am not sure how to convert this correctly. I'll guess I need your input from the failing build. Blindfolded programming is hard... 😞 Really annoying that the CI build logs are not available to contributors....

**Comment by erikgb** [comment]
@JumaX @domenicbove If we can get the build through successfully, I think we are ready for a review on this PR.

**Comment by JumaX** [comment]
@erikgb I think there is an issue with the test job on Jenkins itself, not convinced there is any issue with your code.  Will try to get this resolved today.

**Comment by erikgb** [comment]
@JumaX Thanks! That would be very nice indeed, because it has been bugging me all weekend.... 😄

**Comment by JumaX** [comment]
@erikgb Have you run any molecule scenarios to confirm this runs locally?  For our Jenkins build we use scenario rbac-scram-custom-rhel and it's failing with the following:

```
start": "2020-10-26 09:52:49.236827",
09:52:51          "stderr": "Could not start Jolokia agent: java.lang.IllegalStateException: Cannot open keystore for https communication: java.net.BindException: Address already in use",
09:52:51          "stderr_lines": [
09:52:51              "Could not start Jolokia agent: java.lang.IllegalStateException: Cannot open keystore for https communication: java.net.BindException: Address already in use"
```
Essentially, when Zookeeper is restarted after its setup, we perform a health check to validate it has quorum before moving on to setting up the Brokers.  We do this across all components.

I suspect by moving the tasks, it's actually broken this functionality.  I would recommend running the scenarios locally to validate this.  The following is a guide on how to do this:

https://github.com/confluentinc/cp-ansible/blob/6.0.0-post/HOW_TO_TEST.md

**Comment by erikgb** [comment]
@JumaX I will see if I can reproduce the problems locally. 👍 @domenicbove Please provide me with some hints to what might be the cause to the problems caused by my refactoring - if you have any! 😄

**Comment by JumaX** [comment]
@erikgb I suspect there is an order of operations problem here as, the jolokia port is already in use, based on the error being thrown. The general recommendation is to run this locally with `--debug` logging enabled on the molecule scenario and determine where the invalid call is coming from.

**Comment by JumaX** [comment]
@erikgb I've managed to clone your repo and branch and I am running the scenario locally now, in the future, it's strongly suggested to test locally before submitting a PR, as we can't always guarantee that we will have the resources to debug locally ourselves.  It's why we have the template which asks for specific testing scenarios and the checkbox  to confirm this has been tested before submitting.

**Comment by JumaX** [comment]
@erikgb @domenicbove this looks like its an actual bug in Ansible itself and that actually having the functionality outside the role is a valid, albeit ugly work around: https://github.com/ansible/ansible/issues/20493

**Comment by erikgb** [comment]
@JumaX Got it! I'll try to get the tests running locally, and use that setup for eventual future PRs. Thanks for your time investigating this! 👍

**Comment by erikgb** [comment]
@JumaX I didn't manage to run the molecule test locally, so I just had to try my best and use your Jenkins build to verify. Now the CI build is green, but I am not very pleased with the workaround to overcome the Ansible bug that you found during your investigation. But please have a look and let me know what you think! The roles are now a bit more selfcontained, but there are still things that should be improved over time. I tested this branch in our CI pipeline, and the warning is now gone...

**Review by JumaX — APPROVED** [review]
@erikgb Great job here!  I see that you changed the handlers to directly reference the task.  It's a good cleanup, with the work around for the Ansible bug implemented.  Also good commenting.

**Review by domenicbove — CHANGES_REQUESTED** [review]
Looks good, but can you make the PR into 6.1.x? That branch should be the same as master, but is the target for our 6.1.0 release.

**Comment by domenicbove** [comment]
@erikgb What were your challenges with molecule? We can't open our CI job up to everyone but do want people to be enabled to run the same scenario as jenkins does so they are not blocked.

**Comment by erikgb** [comment]
> Looks good, but can you make the PR into 6.1.x? That branch should be the same as master, but is the target for our 6.1.0 release.

@domenicbove Thx, changed base to 6.1.x

**Comment by erikgb** [comment]
> @erikgb What were your challenges with molecule? We can't open our CI job up to everyone but do want people to be enabled to run the same scenario as jenkins does so they are not blocked.

@domenicbove It might be related to my Docker-based local development environment. Our company only delivers Windows workstations, and I cannot stand it! Your tests are using Docker, so we'll get dind (Docker-in-Docker) here, and we all know how well that works sometimes.... 😅 I am probably going to look closer at it, but I do not have the bandwidth right now. Anyway, this is the last part of my log when failing:
```log
    TASK [Build an Ansible compatible image (new)] *********************************
    FAILED - RETRYING: Build an Ansible compatible image (new) (3 retries left).
    FAILED - RETRYING: Build an Ansible compatible image (new) (2 retries left).
    FAILED - RETRYING: Build an Ansible compatible image (new) (1 retries left).
    failed: [localhost] (item=molecule_local/geerlingguy/docker-centos7-ansible) => {"ansible_loop_var": "item", "attempts": 3, "changed": false, "item": {"ansible_index_var": "i", "ansible_loop_var": "item", "changed": false, "checksum": "6414ef8a4a0894f3
7dd5ec87ae9d1c35676c833f", "dest": "/home/erikbo/.cache/molecule/confluent.test/archive-plain-rhel/Dockerfile_geerlingguy_docker_centos7_ansible", "diff": {"after": {"path": "/home/erikbo/.cache/molecule/confluent.test/archive-plain-rhel/Dockerfile_geerlin
gguy_docker_centos7_ansible"}, "before": {"path": "/home/erikbo/.cache/molecule/confluent.test/archive-plain-rhel/Dockerfile_geerlingguy_docker_centos7_ansible"}}, "failed": false, "gid": 1000, "group": "erikbo", "i": 0, "invocation": {"module_args": {"_di
ff_peek": null, "_original_basename": "Dockerfile.j2", "access_time": null, "access_time_format": "%Y%m%d%H%M.%S", "attributes": null, "backup": null, "content": null, "delimiter": null, "dest": "/home/erikbo/.cache/molecule/confluent.test/archive-plain-rh
el/Dockerfile_geerlingguy_docker_centos7_ansible", "directory_mode": null, "follow": false, "force": false, "group": null, "mode": null, "modification_time": null, "modification_time_format": "%Y%m%d%H%M.%S", "owner": null, "path": "/home/erikbo/.cache/mol
ecule/confluent.test/archive-plain-rhel/Dockerfile_geerlingguy_docker_centos7_ansible", "recurse": false, "regexp": null, "remote_src": null, "selevel": null, "serole": null, "setype": null, "seuser": null, "src": null, "state": "file", "unsafe_writes": nu
ll}}, "item": {"command": "", "groups": ["zookeeper"], "hostname": "zookeeper1.confluent", "image": "geerlingguy/docker-centos7-ansible", "name": "zookeeper1", "networks": [{"name": "confluent"}], "privileged": true, "volumes": ["/sys/fs/cgroup:/sys/fs/cgr
oup:ro"]}, "mode": "0600", "owner": "erikbo", "path": "/home/erikbo/.cache/molecule/confluent.test/archive-plain-rhel/Dockerfile_geerlingguy_docker_centos7_ansible", "size": 1022, "state": "file", "uid": 1000}, "msg": "Error building molecule_local/geerlin
gguy/docker-centos7-ansible - code: 1, message: The command '/bin/sh -c if [ $(command -v apt-get) ]; then DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y python3 sudo bash ca-certificates iproute2 python3-apt aptitude && apt-get clean;
     elif [ $(command -v dnf) ]; then dnf makecache && dnf --assumeyes install /usr/bin/python3 /usr/bin/python3-config /usr/bin/dnf-3 sudo bash iproute && dnf clean all;     elif [ $(command -v yum) ]; then yum makecache fast && yum install -y /usr/bin/py
thon /usr/bin/python2-config sudo yum-plugin-ovl bash iproute && sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf && yum clean all;     elif [ $(command -v zypper) ]; then zypper refresh && zypper install -y python3 sudo bash iproute2 && zypper clean -a;
 elif [ $(command -v apk) ]; then apk update && apk add --no-cache python3 sudo bash ca-certificates;     elif [ $(command -v xbps-install) ]; then xbps-install -Syu && xbps-install -y python3 sudo bash ca-certificates iproute2 && xbps-remove -O; fi' retur
ned a non-zero code: 1, logs: ['Step 1/2 : FROM geerlingguy/docker-centos7-ansible', '\\n', ' ---> a727967c4d1d\\n', \"Step 2/2 : RUN if [ $(command -v apt-get) ]; then DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y python3 sudo bash c
a-certificates iproute2 python3-apt aptitude && apt-get clean;     elif [ $(command -v dnf) ]; then dnf makecache && dnf --assumeyes install /usr/bin/python3 /usr/bin/python3-config /usr/bin/dnf-3 sudo bash iproute && dnf clean all;     elif [ $(command -v
 yum) ]; then yum makecache fast && yum install -y /usr/bin/python /usr/bin/python2-config sudo yum-plugin-ovl bash iproute && sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf && yum clean all;     elif [ $(command -v zypper) ]; then zypper refresh && zypper
 install -y python3 sudo bash iproute2 && zypper clean -a;     elif [ $(command -v apk) ]; then apk update && apk add --no-cache python3 sudo bash ca-certificates;     elif [ $(command -v xbps-install) ]; then xbps-install -Syu && xbps-install -y python3 s
udo bash ca-certificates iproute2 && xbps-remove -O; fi\", '\\n', ' ---> Running in ed04bdb7d96a\\n', 'Loaded plugins: fastestmirror, ovl\\n', 'Determining fastest mirrors\\n', '\\x1b[91m\\n\\n One of the configured repositories failed (Unknown),\\n and yu
m doesn\\'t have enough cached data to continue. At this point the only\\n safe thing yum can do is fail. There are a few ways to work \"fix\" this:\\n\\n     1. Contact the upstream for the repository and get them to fix the problem.\\n\\n     2. Reconfig
ure the baseurl/etc. for the repository, to point to a working\\n        upstream. This is most often useful if you are using a newer\\n        distribution release than is supported by the repository (and the\\n        packages for the previous distributi
on release still work).\\n\\n     3. Run the command with the repository temporarily disabled\\n            yum --disablerepo=<repoid> ...\\n\\n     4. Disable the repository permanently, so yum won\\'t use it by default. Yum\\n        will then just ignor
e the repository until you permanently enable it\\n        again or use --enablerepo for temporary usage:\\n\\n            yum-config-manager --disable <repoid>\\n        or\\n            subscription-manager repos --disable=<repoid>\\n\\n     5. Configure
 the failing repository to be skipped, if it is unavailable.\\n        Note that yum will try to contact the repo. when it runs most commands,\\n        so will have to try and fail each time (and thus. yum will be be much\\n        slower). If it is a ver
y temporary problem though, this is often a nice\\n        compromise:\\n\\n            yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true\\n\\nCannot retrieve metalink for repository: epel/x86_64. Please verify its path and try again\\n\
\x1b[0m', 'Removing intermediate container ed04bdb7d96a\\n']"}
```

**Review by domenicbove — APPROVED** [review]
LGTM

**Comment by domenicbove** [comment]
Oh windows does not sound fun! It looks like its failing to docker build... one thing you can do is
```
cp Dockerfile.j2 Dockerfile

## replace the top line with:
FROM geerlingguy/docker-centos7-ansible

docker build .
```
And you'll see the logs, but based off of what you just sent me, it looks like it's going to say: `Cannot retrieve metalink for repository: epel/x86_64. Please verify its path and try again`

Alternatively, the dockerfiles aren't really needed, they are just meant to speed up the dev time by having the packages pre installed.
You can comment out the dockerfile lines in the molecule.yml file in the scenarios you want to run:
```
# dockerfile: ../Dockerfile.j2
```
And it should still work!

**Comment by domenicbove** [comment]
@erikgb Apologies for not merging and creating merge conflict. Do you mind resolving the conflicts and then I will go ahead and merge this PR next.

**Comment by erikgb** [comment]
@domenicbove I have rebased now - best effort. Let's see how the CI build responds. Some nasty conflicts to resolve, so I might need your assistance with eventual CI job output....

**Pull request merged**
