### PR TITLE
[ANSIENG-3627] | updated min ansible version in runtime & meta

### PR DESCRIPTION
**Pull request by rrbadiani**
# Description

Added patch version to meta/runtime.yml & updated min ansible version in role's meta/main.yml
Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

# Checklist:

- [ ] Any variable/code changes have been validated to be backwards compatible (doesn't break upgrade)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If required, I have ensured the changes can be discovered by cp-ansible discovery codebase
- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by mansisinha** [comment]
Starting 7.7, we need to update the minimum version to 2.15 since 2.14 will be deprecated before 7.7 release

**Comment by rrbadiani** [comment]
> Starting 7.7, we need to update the minimum version to 2.15 since 2.14 will be deprecated before 7.7 release

yes we need to do that but I thought that minimum version upgrade can be brought as part of that epic itself. Currently upgrading it would mean we would have to run all the tests on it on ansible 9 which we dont support as of now but will be supporting in few days

**Comment by mansisinha** [comment]
> > Starting 7.7, we need to update the minimum version to 2.15 since 2.14 will be deprecated before 7.7 release
> 
> yes we need to do that but I thought that minimum version upgrade can be brought as part of that epic itself. Currently upgrading it would mean we would have to run all the tests on it on ansible 9 which we dont support as of now but will be supporting in few days

updating meta runtime will not affect our tests, it will only throw a warning

**Comment by mansisinha** [comment]
Please resolve the conflicts before merging

**Pull request closed without merging**
