### PR TITLE
Fix ansible version compare

### PR DESCRIPTION
**Pull request by utkarsh5474**
# Description

Validate >=2.11 and <2.13 which will include all 2.11.x and 2.12.y

Fixes # (issue)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

**Test Configuration**:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] Any variable changes have been validated to be backwards compatible

### CODE REVIEW

**Review by anuj-apdev — APPROVED** [review]
LGTM.

**Review by nsharma-git — APPROVED** [review]

**Comment by erikgb** [comment]
Why don't we allow Ansible version >= 2.11? I am getting:

````
TASK [confluent.platform.common : Verify Ansible version] **********************
fatal: [REDACTED]: FAILED! => changed=false 
  assertion: ansible_version.full is version('2.13', '<')
  evaluated_to: false
  msg: '"You must update Ansible to 2.11 or 2.12 to use these playbooks."'
````

Using `ansible [core 2.13.4]`. Is this intentional?

**Comment by erikgb** [comment]
> Why don't we allow Ansible version >= 2.11? I am getting:
> Using `ansible [core 2.13.4]`. Is this intentional?

Seems so, ref. https://github.com/confluentinc/cp-ansible/pull/1165

@utkarsh5474 Can you elaborate the "issues" before we start downgrading to Ansible 2.12? We run 7.2.1 with Ansible 2.13 without any issues.

**Comment by utkarsh5474** [comment]
Hey @erikgb. Apologies for not being descriptive. 
Sharing a few errors which users faced specifically with 2.13 (these issues moved away when downgraded to 2.12, 2.11) 

```
TASK [confluent.platform.ssl : Create Openssl Config for SAN] ************************************************************************************************************************************************
[WARNING]: Falling back to Ansible unique filter as Jinja2 one failed: 'ansible_ssh_host' is undefined
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.errors.AnsibleUndefinedVariable: {{ [inventory_hostname, ansible_fqdn, ansible_host, ansible_ssh_host, hostname|default(omit)] | unique }}: 'ansible_ssh_host' is undefined
fatal: [ec2-18-118-14-13.us-east-2.compute.amazonaws.com]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: {{ [inventory_hostname, ansible_fqdn, ansible_host, ansible_ssh_host, hostname|default(omit)] | unique }}: 'ansible_ssh_host' is undefined"}
```

Templating issues
```
TASK [confluent.platform.kafka_broker : Remove Duplicates and Convert to String] *** task path: /root/.ansible/collections/ansible_collections/confluent/platform/roles/kafka_broker/tasks/rbac.yml:32 Tuesday 23 August 2022 15:41:09 -0500 (0:00:00.383) 0:02:23.850 ******** ok: [xyz] => {  "ansible_facts": {  "super_users": "[;';U;s;e;r;:;a;x;y;z;a;b;c;d;]; ;+;c;p;-;k;f"
```

**Comment by erikgb** [comment]
Thanks @utkarsh5474! Are there any efforts to fix the issues with the latest Ansible version? It just don't feel right to downgrade, but we seem forced to it now - if not disabling validations completely.

**Comment by utkarsh5474** [comment]
Yeah, I think we should be able to fix it by next patch (due sometime in december). We haven't estimated the exact work required here.

**Comment by sknop** [comment]
Hi Erik

The problem we encountered with Ansible 2.13 appeared when we tried to install RBAC via cp-ansible. For some reason the setting super.users changes from

	super.users:	User:admin,User:kafka

to

	super.users: ‘U’,’s’,’e’,’r;’ … and so on

Since Ansible is written in Python, this is a well-known issue of Python interpreting a string as a list[bytes] in some circumstances. We simply have not found that bit in our Ansible setup yet that triggered this regression from 2.12 to 2.13 - once this is found and fixed, using Ansible 2.13 should be possible again (unless of course, we find another regression).

So, no RBAC—> Ansible 2.13 is fine. If you decide to install RBAC at a later stage with Ansible 2.13, your setup will blow up.

Cheers,

Sven Erik
--
Sven Erik Knop
Confluent
Data in Motion
Sven Erik Knop
Team Lead Professional Services EMEA
 +44 (0)7974 351514

Follow us:  Blog • Slack • Twitter • YouTube

**Pull request merged**
